### ISSUE TITLE
No obvious public admin function to remove access

### ISSUE THREAD

**Issue by POMA-Chris** [Cpollo/Ethereum#2]
https://github.com/Cpollo/Ethereum/blob/335aa6e4c7de9fbb2c8da942da07456d2f721ec4/contracts/access/CpolloRole.sol#L46

**Comment by JoaoCampos89** [comment]
This is under investigation. I want to use this function to remove Cpollo members as well by the owner address. But it will be extremely danger give that power to solely one person. The best approach it will be create a multisig owner address.
